
services:
  web:
    build: .
    command: npm start
    image: nginx
    volumes:
    - '.:/app'
    - '/app/node_modules'
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    - NODE_ENV=development
    depends_on:
      - node
  node:
    image: node
    